export const cartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDENN',
    ADD_ITEM: "ADD_ITEM",
    REMOVE_ITEM: "REMOVE_ITEM",
    DECREASE_ITEM: "DECREASE_ITEM",
    CLEAR_CART: 'CLEAR_CART'
}