const userActionTypes = {
    GOOGLE_SIGNIN_START: 'GOOGLE_SIGNIN_START',
    SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
    SIGNIN_FAILURE: 'SIGNIN_FAILURE',
    EMAIL_SIGNIN_START: 'EMAIL_SIGNIN_START',
    CHECK_CURRENT_USER: 'CHECK_CURRENT_USER',
    SIGNOUT_START: 'SIGNOUT_START',
    SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
    SIGNOUT_FAILURE: 'SIGNOUT_FAILURE',
    SIGNUP_START: 'SIGNUP_START',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE'
} //就是一个object不是方法

export default userActionTypes;